### ISSUE TITLE
Compare different providers practices

### ISSUE THREAD

**Issue by almereyda** [libresh/awesome-librehosters#7]
As far as they are open, like on 
- http://commonsnetwork.eu/wp-content/uploads/2015/10/Navarro-IntroCommonsGovernance-europarl-1.pdf

via 
- http://commonsnetwork.eu/events/

**Comment by pierreozoux** [comment]
What do you mean exactly?
Do you mean that we should find a way to compare Hosting providers?

**Comment by almereyda** [comment]
Yes, I believe we should create an evaluation matrix which allows us to compare different providers practices and structural organization.

**Comment by pierreozoux** [comment]
This is linked to https://openintegrity.org/en

**Comment by almereyda** [comment]
Well, I think we could also at least list the services which are offered, few prices and subscription models and the estimated size of the collective?

**Comment by almereyda** [comment]
In #14 a first attempt of a comparison matrix has been started by introducing the scale of *office location*, which brings in a geographic scope.

While discussing in [`#freenode_#freie-gesellschaft:matrix.org` today](https://matrix.to/#/!ozhrkuhXIdlgTMPRgD:matrix.org/$15015419094994520oCMnE:matrix.org), we have found that many IT collectives not neccesarily provide hosting. With the introduction of the headline *non-solidarity, nonetheless FLOSS collectives* I had introduced another quality to check for.

Further on in the discussion the idea sprung up to curate the list in Wikidata or the [Transformaps Wikibase](https://base.transformap.co/), we're still talking solidarity economies here, and only then generate some MarkDown from it.

**Comment by pierreozoux** [comment]
Yeah, I understand what you say.
Bascially, we are duplicating the effort with CHATONS, somehow...

CHATONS is using a drupal db, and we are using.. md database.

Maybe we could create a json, and render this json into a nice website, and then CHATONS could consume this json too?

I don't know what is the best, I'll drop this into the CHATONS mailing list.

**Comment by almereyda** [comment]
Do you want my honest answer?

I think we could use Wikidata or Wikibase in some place, as such we have a free schema, can always extend the graph with new facts and still have all data available as JSON.

**Comment by pierreozoux** [comment]
it actually sounds good!
Could we have the git workflow?
Can we query from the browser?
Let's have a call :)

**Comment by maxlath** [comment]
The issue with Wikidata is that [everything can't get in Wikidata](https://www.wikidata.org/wiki/Wikidata:Notability): some software will be there (ex: [Ethercalc](https://wikidata.org/entity/Q3059271), [Mastodon](https://wikidata.org/entity/Q27986619), [RocketChat](https://wikidata.org/entity/Q24050001)), others not (examples from your [shop](https://indie.host/shop/), Mautic, Reveal.js, Laverna). So, linking to Wikidata is definitely a good thing, because you can generate links to all sorts of other databases (forges, social networks, app stores, etc), but you will probably need to complete those data with your own database(?).

In any case, have a look to the [WikiProject Informatics](https://www.wikidata.org/wiki/Wikidata_talk:WikiProject_Informatics)

**Comment by almereyda** [comment]
In short: if we want to use Wikidata, it's a mess, if we use our own Wikibase, we can do whatever we want?

**Comment by maxlath** [comment]
whatever you want, except the one thing we are all waiting for: re-use existing Wikidata properties and items out of the box \o/

**Comment by pierreozoux** [comment]
Maybe stupid question, but how LinkedData and wikidata are, well, linked?
Do you have links for me to consume, and try to understand?

I just rewatched:
https://www.ted.com/talks/tim_berners_lee_on_the_next_web

**Comment by maxlath** [comment]
* [Introducing Wikidata to the Linked Data Web](http://korrekt.org/papers/Wikidata-RDF-export-2014.pdf): a 2014 paper on the matter; since then, the most notable progress in terms of LOD has been the [SPARQL endpoint](https://query.wikidata.org/) (see [help center](https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/Wikidata_Query_Help))
* [Wikidata:Data access](https://www.wikidata.org/wiki/Wikidata:Data_access#Linked_Data_interface)
* [Wikidata: The New Rosetta Stone](http://lab.cccb.org/en/wikidata-the-new-rosetta-stone/)
(might add more later)

**Comment by pierreozoux** [comment]
Interesting:
https://joinup.ec.europa.eu/page/adms

**Comment by pierreozoux** [comment]
Thanks @maxlath for your input.

It looks to me, that wikidata is a subcategory of LOD.
And because of `Notability` there will be a lot of frictions with wikidata to incorporate any application or service provider.

I also don't see the point of using Mediabase, as it would mean, centralizing data, and the web was not designed this way.

Reading a bit, I think LOD is the best way to achieve our goal.
And the information should be located in the service provider, or web application website, not our database of any sort.

Reading https://schema.org, looks like we have almost everything we need:
 - http://schema.org/WebApplication
 - http://schema.org/ProfessionalService

Then, I guess, the only work that is left is:
 - show the example
 - PR/convince app dev, and service provider to follow this practice

Then, our list of http URL is actually the best way to solve our problem.
So we actually choosed the best way without knowing :)

What do you think?

**Comment by y0va** [comment]
Probably thats the way to go. 
But by learning from https://github.com/indiehosters/awesome-librehosters/issues/13 we actually should propose the boolean property http://schema.org/islibre and its addition to http://schema.org/Organization if we want to harden the unique feature of being `libre` which is a quite interesting political goal within the commons debate.

If we don't want this fight, maybe a statement in http://pending.schema.org/ethicsPolicy would allow us to determine the level of libreness of a hoster.

**Comment by pierreozoux** [comment]
Yes, I think we'll need to extend the schema to add specifics related to our organizations and the way we operate them.

but various things here:
For instance CHATONS will gather the ethical hosters that sign the chart.
But we could say that the hoster can use the `memberOf` chatons. But then you'll need to verify on the CHATONS site that it is an accepted CHATONS.

And for the libre part:
ethicsPolicy is probably enough for the hoster to state there that they are using only free software.
But for the source code of the organization, I believe it is also important that the hoster share its recipes.
For instance, we could use:
http://schema.org/SoftwareApplication
And this would describe the application that runs the hoster.
And if you want to clone the hoster, it would be easier :)
But I don't see the features like `sourceCode` or `support` we could try to add them, or maybe they are somewhere else.

But I have a more meta question, how do we don't this conversation in a better way, what do you think about a discourse?
I'm thinking about `forum.chatons.org` and we could continue this discussion in a category like `Catalog`. There we could exchange on the challenges that come with this project?

**Comment by almereyda** [comment]
Let's keep in mind which problem we are trying to solve here. Or at least I should update the OP to reflect the course of discussion, I don't know.

In chatting elsewhere the conversation cycled around two motives:

(1) users come to a hosters page and get a list of services and conditions
(2) federated service producers may want to ship their related apps with a directory of hosters for their self-hostable offer

A very similar idea popped up at https://github.com/matrix-org/matrix.org/issues/95#issuecomment-369552029 these days.

**Comment by pierreozoux** [comment]
Closing in favor of https://github.com/libresh/catalog

**Comment by almereyda** [comment]
Reopening since this issue is not soley about a catalogue of services or hosters, but about methodologies and aspects to compare between different organisations. This is why I suggested to either rename the issue to what it has developed into, or to breaking those parts out.

I am still interested in a comparison matrix of ways of self-organisation, bookkeeping, accounting, membership and public communication, legal forms, etc. as above. The readme of the libresh/catalogue also does not mention those aspects, which had initially been introduced here, why it's good to keep track of those ideas, instead of purging them.

**Comment by pierreozoux** [comment]
@almereyda My idea is to start to have a schema, and iterate over time. I don't think we can have the perfect schema right away, we'll need a lot of iteration.

**Comment by maxlath** [comment]
presentation on software data in Wikidata that could be of interest here: Pathways for discovery of free software [video](https://media.libreplanet.org/u/libreplanet/m/pathways-for-discovery-of-free-software/) / [slides](https://commons.wikimedia.org/wiki/File:Pathways-discovery-free.pdf)

**Comment by almereyda** [comment]
After picking out the the relevant aspect into a separate issue and reusing an existing one, I am happy to close here in favour of.

- https://github.com/libresh/catalogue/issues/7
- https://github.com/libresh/catalogue/issues/9
